version: '2'

services:
  nfivehub:
    image: node:latest
    command: "npm start"
    working_dir: /app
    links:
     - db
    volumes:
     - .:/app
    ports:
     - "3000:80"
    environment:
     - NODE_ENV=docker

  db:
    image: mongo:latest
    command: "--smallfiles"
    volumes:
     - ./db:/data/db
    expose:
     - 27017
    ports:
     - "27017:27017"
